version: "3.9"
services:
  ethstats:
    build:
      context: ../ethstats-server
    ports:
      - "3000:3000"
    environment:
      - WS_SECRET=test
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
    depends_on:
      - ethstats

